name: Windows (Build and test)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/checkout@v7
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...